[package]
name = "lswd"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
nix.workspace = true
serde.workspace = true
tokio.workspace = true
tokio-stream = { workspace = true, features = ["net"] }
toml.workspace = true
tonic.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
lsw-lib = { path = "../lsw-lib" }
lsw-qemu = { path = "../lsw-qemu" }
