[package]
name = "lsw-lib"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
chrono.workspace = true
dirs.workspace = true
nix = { version = "0.29", features = ["user"] }
prost.workspace = true
serde.workspace = true
thiserror.workspace = true
toml.workspace = true
tonic.workspace = true
uuid.workspace = true

[build-dependencies]
tonic-build = "0.12"
